
import { Meal } from '@/types';

export const mealData: Meal[] = [
  {
    id: '1',
    name: 'Breakfast',
    type: 'breakfast',
    calories: 420,
    protein: 25,
    carbs: 45,
    fat: 15,
    date: new Date(),
    items: [
      {
        id: '101',
        name: 'Greek Yogurt',
        servingSize: '200g',
        calories: 130,
        protein: 20,
        carbs: 7,
        fat: 2,
      },
      {
        id: '102',
        name: 'Mixed Berries',
        servingSize: '100g',
        calories: 50,
        protein: 1,
        carbs: 12,
        fat: 0,
      },
      {
        id: '103',
        name: 'Whole Grain Toast',
        servingSize: '2 slices',
        calories: 180,
        protein: 8,
        carbs: 30,
        fat: 2,
      },
      {
        id: '104',
        name: 'Almond Butter',
        servingSize: '15g',
        calories: 60,
        protein: 2,
        carbs: 2,
        fat: 11,
      },
    ],
  },
  {
    id: '2',
    name: 'Lunch',
    type: 'lunch',
    calories: 650,
    protein: 35,
    carbs: 70,
    fat: 20,
    date: new Date(),
    items: [
      {
        id: '201',
        name: 'Grilled Chicken',
        servingSize: '150g',
        calories: 240,
        protein: 45,
        carbs: 0,
        fat: 6,
      },
      {
        id: '202',
        name: 'Quinoa',
        servingSize: '100g cooked',
        calories: 190,
        protein: 8,
        carbs: 34,
        fat: 3,
      },
      {
        id: '203',
        name: 'Mixed Salad',
        servingSize: '100g',
        calories: 25,
        protein: 2,
        carbs: 5,
        fat: 0,
      },
      {
        id: '204',
        name: 'Avocado',
        servingSize: '1/2 medium',
        calories: 120,
        protein: 2,
        carbs: 6,
        fat: 11,
      },
      {
        id: '205',
        name: 'Olive Oil Dressing',
        servingSize: '15ml',
        calories: 75,
        protein: 0,
        carbs: 0,
        fat: 9,
      },
    ],
  },
  {
    id: '3',
    name: 'Dinner',
    type: 'dinner',
    calories: 550,
    protein: 30,
    carbs: 45,
    fat: 22,
    date: new Date(),
    items: [
      {
        id: '301',
        name: 'Baked Salmon',
        servingSize: '150g',
        calories: 294,
        protein: 30,
        carbs: 0,
        fat: 15,
      },
      {
        id: '302',
        name: 'Sweet Potato',
        servingSize: '150g',
        calories: 135,
        protein: 2,
        carbs: 31,
        fat: 0,
      },
      {
        id: '303',
        name: 'Broccoli',
        servingSize: '100g',
        calories: 55,
        protein: 4,
        carbs: 11,
        fat: 0,
      },
      {
        id: '304',
        name: 'Olive Oil',
        servingSize: '10ml',
        calories: 90,
        protein: 0,
        carbs: 0,
        fat: 10,
      },
    ],
  },
  {
    id: '4',
    name: 'Snack',
    type: 'snack',
    calories: 200,
    protein: 5,
    carbs: 25,
    fat: 10,
    date: new Date(),
    items: [
      {
        id: '401',
        name: 'Mixed Nuts',
        servingSize: '30g',
        calories: 180,
        protein: 5,
        carbs: 10,
        fat: 10,
      },
      {
        id: '402',
        name: 'Apple',
        servingSize: '1 medium',
        calories: 72,
        protein: 0.4,
        carbs: 19,
        fat: 0.2,
      },
    ],
  },
];
